language: php
php:
  - 7.2
before_script: composer install
script: phpunit tests
after_script: npm run build
deploy:
  provider: heroku
  #  app: APP_NAME
  on: master
  #  api_key:
  #    secure: ENCRYPTED_API_KEY
