language: php
php:
- 7.2
before_script:
  - composer install
  - npm install
  - npm run build
script: echo 'none'
deploy:
  provider: heroku
  app: s4t5
  on: master
  skip_cleanup: true
  api_key:
    secure: EhZQKD01aSoEn3rVYtACf9fXEKTVoFUyesLlMLwuqP3mz4Rripoxs6kztgGfbYvEZOd/7Fkwv+Wo3jSMJyMxT+ISTPjjJbygBosifOWEm1abxJ04BsDHN2yw2vHe3TkQmmHKmuuNOOxEie6kScGNNfNMifiNL/9T57x0yGdI9QPR+tLlgyg50Sddat607fSI2U/ObH7InvRRh/kTZIBc/QAhTw0o2qyA6lEQPlR7eqjfPw9GOVUCB9iU6eIZdj1FwsUrR1aAyp9xj0DuZZpdyMrnbrvH2abkuPgEU9HDSyxEcs45cGhpHbaaWKu4CUrmtPtLnXrEwiwCpnouqQQJR78hLMmYXu4OAVRdriYpUlwjXe1+z64U0SzcAkREaDJsla8hbhzmOBR41NDscNox+Uy283sDk7Y8ZaLnn5Hsg5mGDDwf1aEyaNgepNgzPcea01qOphwmvv6IYiwTzWxdqQEUsJpoERWeStBv5Id2sFBndj1rzbV/YaTCRw+jFTjv+ELsh+rfAvPh+fBG1YZPythnF4ZuTC96kl3exLSlI+LYJHAKC4gv0s39sXUQkzjJAontMLGnalBwUj7c0frNPuO3YJJdgOu/hytOE0/Q4HKtdySYj20poDfxuaF6a+GqFIp48AY3oBB5ntPDCyNocrxEOXNDwQYjoOUglQ55MIA=
