language: php
php:
- 7.2
before_script:
  - composer install
  - npm install
  - npm run build
script: echo 'none'
deploy:
  provider: heroku
  app: testvuecollection
  on: master
  skip_cleanup: true
  api_key:
    secure: OC1Lbc5D7QCDgqmPzihJKNct4QEtRsNJIJgr5/PROJCir1Y2Pq+njTkr2q9MU9cer1HV995G8SLSpknHpVAtl8Q8nx/hLEXutfqJOmH3JP+hBt4kZ5jrJUpyjg38l8ohA4FUg8NcKsHvKcw6dJUt9c/Zq1PWnN1KPlRBymbbt5aXXWrHzhWqgvj10ObiMeBcRpuzOsbF9hfm3vlAIjxjtB91G6iPOn+QUP0/Pm2C9I23DTFVzdcGnaYAGL2ntfY8xi+LpmfkeEtFLF6JobNE1ZQRgK7A2+JAo9aKocCCgC1WCHbnsacdi5r06zpXlayYBE0MDY23GLSe3HF5SPv8277FNAMUA1bzl+7V6kVBHx9h7XY30wF1SUewsET3S4uJGKSAvtyfJcd6SfzpmTfXj1geyal5fHdPRvoqZc2uBQQvPxM4l2Zc2Kcvs2K4chaALXkJqTBE8nlUJ/aklRGkIgoSIr7ijIKmm2uA/ePxhX2HBiZ//whsHHOAyFPnp3TmSgT374SNSo/hi7JGmHC3OrjzWr9HsPYTzdNFcnEgsUHHma3abJ2A8a376XiyjQpJNeSmncrVsZIJ5UlteGH6V7i98TV8Ng2NCvV/wjnlwmEbVDCV605MtG5EikomwUpX1HJyS2ArsyOCBusHKYv1m9Zrk0IcScvv+IPCcC2SPWo=
