language: php
php:
- 7.2
before_script:
  - composer install
  - npm install
  - npm run build
script: echo 'none'
deploy:
  provider: heroku
  app: testvuecollection
  on: master
  skip_cleanup: true
  api_key:
    secure: USz7MZ9ZG1gSilhGJIcYww1oVHXL7Q2ru/HH24JpJRkE6rTw9JJRlZIsb9BKiKrMQ/asqlbYW2yGKvFmgTZqqG31m9pYEETRs9NFtNMHrxyOR2cE8ShtuTjUABeNV5FPIov0DDrLrDPPgqfc/ILcU8n1H1br3ANuYG5u0fW0/5BtRwCaSlrUSYWUClOUSF5es8NZtFnaOZgpmjU1UaCWs3P+lsG8WgFY3ckat/38qKhhMkV8IzAlEMcpc8hwIgGG0zNKVGg3DXLmwpayEPI/Qp43u/omARgyoRxdB91BE7Kdvnr0E6BBWEmrLhLLB8v4eGu030Z1Q7a8wkkbgHCRB13Xmh4n+Pkp0/n1v52iZ2vQa8gX//glbswgmFVAsPcZYYmeqcBj8KyjMo/f5Afg0kiv/5lajjGCoQQJQ1s6YsePQOnxUjcl2IO+b9CBncy2hcPqi1sKt71eao3jbHEumpjM00GyhFiqOXn8rGYDtdbqLUPb7BCMe41yV2SHDPQ4MFCc5KK2rIhJ69Htct6RXFzh6M9qfPV4gEYmG/2a/0pPTmtALllahZ9A+mv9vd8d8hTw6B+X3egOnw3+e6qsqZeqGH8+G5ita4NoR7uO/8c+tD351Txrwg7tHyEq6Kg3YzMpSqfzdCrT3iUppOvSuWKoUpahmYpnBlIRKO/In/s=
